### ISSUE TITLE
Tabs display error on Firefox Linux.

### ISSUE THREAD

**Issue by apathy-dude** [clevett/Shadowrun-5e#10]
There's a display issue, as seen below, when running Firefox on Linux.

![screenshot_2018-10-29 sr test roll20](https://user-images.githubusercontent.com/1674411/47625437-9702f500-dafb-11e8-8fd5-b659ed2b01b0.png)

Investigating this I noticed the tabs are using absolute values which have never really sat right with me so I came up with a small refactor solution involving flex box:

``` html
<!-- Most buttons switch to this format.  Not sure if label is needed for clicking properly, just the way I've always done it -->
<input type="radio" id="tab-core" name="attr_tab" value="core" title="Core Sheet" />
<label class="btn" for="tab-core">
	<span data-i18n="core">Core</span>
</label>

<!-- While similar to above this version uses the icon-img which changes the text-family to pictos -->
<input type="radio" id="tab-opt" name="attr_tab" value="options" title="Sheet Options" checked="checked"/>
<label for="tab-opt" class="btn" for="tab-core">
	<span class="icon-img">y</span>
</label>

```

``` css
/* Commented out this to get fonts to work properly for buttons, might cause issues else where
	input[type="checkbox"] + span {
		font-family: pictos;}
*/

.sheet-icon-img {
	font-family: pictos;
	font-size: medium;
}

.sheet-tabs {
	position: relative;
	top: 60px;
	z-index: 1;
	display: flex;
	flex-flow: row nowrap;
	justify-content: space-between;
}

.sheet-tabs > * {
	margin: 0;
	padding: 0;
}

.sheet-tabs input {
	display: none;
}

.sheet-tabs .sheet-btn {
	border-radius: 5px;
	border: 1px solid #000;
	padding: 3px;
}

.sheet-tabs input[type="radio"]:checked + label,
.sheet-tabs input[type="checkbox"]:checked + label {
    background-color: #610b0d;
    color: #fff;
}
```

There is a bug with the version I worked on though resulting in the pictos icon being uppercased into the heartbeat instead of gear.  Didn't investigate what caused that since it's still lower case in the text.

![screenshot_2018-10-29 sr test roll20 1](https://user-images.githubusercontent.com/1674411/47626949-07157900-db04-11e8-87a4-d2559b511968.png)
